import React, { useEffect, useMemo, useRef, useState } from "react";
import * as echarts from "echarts";
const SERIES=[{key:"Tur Geliri",color:"#10b981"},{key:"Tur Masrafı",color:"#f97316"},{key:"Bahşiş",color:"#8b5cf6"},{key:"Komisyon",color:"#3b82f6"}];
const parseDate=v=>new Date(`${v}T12:00:00`); const money=(v,c="TRY")=>new Intl.NumberFormat("tr-TR",{style:"currency",currency:c,maximumFractionDigits:0}).format(Number(v)||0);
const start=(date,mode)=>{const d=new Date(date);d.setHours(12,0,0,0);if(mode==="year")d.setMonth(0,1);else if(mode==="month")d.setDate(1);else if(mode==="week")d.setDate(d.getDate()-((d.getDay()+6)%7));return d};
const key=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
const next=(d,mode)=>{const x=new Date(d);if(mode==="year")x.setFullYear(x.getFullYear()+1);else if(mode==="month")x.setMonth(x.getMonth()+1);else x.setDate(x.getDate()+7);return x};
const label=(d,mode)=>new Intl.DateTimeFormat("tr-TR",mode==="year"?{year:"numeric"}:{month:"short",year:"2-digit"}).format(d);
export default function AnalyticsChart({rows,currency="TRY",convert}){const ref=useRef(null);const[mode,setMode]=useState("month");const data=useMemo(()=>{const paid=rows.filter(r=>r.status==="Ödendi"&&SERIES.some(s=>s.key===r.type));if(!paid.length)return[];const dates=paid.map(r=>parseDate(r.date)).sort((a,b)=>a-b),first=start(dates[0],mode),last=start(dates[dates.length-1],mode),out=[];for(let d=new Date(first);d<=last;d=next(d,mode)){const item={key:key(d),label:label(d,mode)};SERIES.forEach(s=>item[s.key]=0);out.push(item)}const map=new Map(out.map(x=>[x.key,x]));paid.forEach(r=>{const item=map.get(key(start(parseDate(r.date),mode)));if(item)item[r.type]+=convert(r)});return out},[rows,mode,convert]);
useEffect(()=>{if(!ref.current)return;const chart=echarts.init(ref.current);chart.setOption({animationDuration:650,color:SERIES.map(s=>s.color),tooltip:{trigger:"axis",valueFormatter:v=>money(v,currency),backgroundColor:"#0f172a",borderWidth:0,textStyle:{color:"#fff"}},legend:{bottom:0,textStyle:{color:"#64748b"}},grid:{left:58,right:20,top:28,bottom:62},xAxis:{type:"category",boundaryGap:false,data:data.map(d=>d.label),axisLine:{lineStyle:{color:"#dbe3ee"}},axisLabel:{color:"#64748b"}},yAxis:{type:"value",axisLabel:{color:"#64748b",formatter:v=>money(v,currency)},splitLine:{lineStyle:{color:"#edf2f7"}}},series:SERIES.map(s=>({name:s.key,type:"line",smooth:true,showSymbol:false,symbolSize:7,emphasis:{focus:"series",showSymbol:true},areaStyle:{opacity:.08},data:data.map(d=>d[s.key])}))});const resize=()=>chart.resize();window.addEventListener("resize",resize);return()=>{window.removeEventListener("resize",resize);chart.dispose()}},[data,currency]);
return <section className="analysis line-chart-panel finance-modern echarts-finance-panel"><div className="analytics-head"><div><span className="eyebrow">FİNANS ANALİZİ</span><h2>Aylık kategori hareketleri</h2><p className="finance-caption">Ödenmiş kayıtlar, dönem bazında profesyonel trend görünümü</p></div><div className="period-tabs">{[["week","Hafta"],["month","Ay"],["year","Yıl"]].map(([v,l])=><button key={v} className={mode===v?"active":""} onClick={()=>setMode(v)}>{l}</button>)}</div></div><div className="echarts-summary">{SERIES.map(s=><span key={s.key}><i style={{background:s.color}}/>{s.key}: <b>{money(data.reduce((sum,d)=>sum+d[s.key],0),currency)}</b></span>)}</div>{data.length?<div ref={ref} className="echarts-finance-chart" role="img" aria-label="Finans trend grafiği"/>:<div className="finance-empty">Grafik için ödenmiş kayıt bulunmuyor.</div>}</section>}
