import React, { useEffect, useMemo, useState } from "react";
const fallback = ["USD/TRY", "EUR/TRY", "GBP/TRY", "ALTIN", "BTC", "ETH"].map((symbol) => ({ symbol, value: null, currency: "TRY" }));
const format = (item) => item.value == null ? "—" : new Intl.NumberFormat("tr-TR", { style: "currency", currency: item.currency || "TRY", minimumFractionDigits: item.value > 10000 ? 0 : 2, maximumFractionDigits: item.value > 10000 ? 0 : 2 }).format(item.value);
export default function MarketTicker() {
  const [items, setItems] = useState(fallback), [updatedAt, setUpdatedAt] = useState(""), [paused, setPaused] = useState(false);
  useEffect(() => { let active = true; const refresh = async () => { try { const response = await fetch(`/api/markets?_=${Date.now()}`, { cache: "no-store" }), data = await response.json(); if (active && response.ok && data.items?.length) { setItems(data.items); setUpdatedAt(data.fetchedAt || new Date().toISOString()); } } catch {} }; refresh(); const timer = setInterval(refresh, 5 * 60 * 1000); return () => { active = false; clearInterval(timer); }; }, []);
  useEffect(() => { const place = () => { const ticker = document.querySelector(".market-ticker-host"), nav = document.querySelector(".global-category-nav-host"); if (ticker && nav && ticker.previousElementSibling !== nav) nav.insertAdjacentElement("afterend", ticker); }; place(); const observer = new MutationObserver(place); observer.observe(document.body, { childList: true, subtree: true }); return () => observer.disconnect(); }, []);
  const repeated = useMemo(() => [...items, ...items], [items]);
  return <div className="market-ticker-host" aria-label="Güncel piyasa verileri"><div className="market-ticker-label"><i/> PİYASALAR <small>{updatedAt ? new Intl.DateTimeFormat("tr-TR", { hour: "2-digit", minute: "2-digit" }).format(new Date(updatedAt)) : "yükleniyor"}</small></div><div className={`market-ticker-window${paused ? " paused" : ""}`} onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)}><div className="market-ticker-track">{repeated.map((item, index) => <div className="market-ticker-item" key={`${item.symbol}-${index}`} aria-hidden={index >= items.length}><span>{item.symbol}</span><strong>{format(item)}</strong>{typeof item.change === "number" ? <small className={item.change >= 0 ? "up" : "down"}>{item.change >= 0 ? "▲" : "▼"} {Math.abs(item.change).toFixed(2)}%</small> : <small>CANLI</small>}</div>)}</div></div></div>;
}
