import React,{useMemo,useState}from'react';

const SERIES=[
 {key:'Tur Geliri',label:'Tur Geliri',className:'income'},
 {key:'Tur Masrafı',label:'Tur Masrafı',className:'expense'},
 {key:'Bahşiş',label:'Bahşiş',className:'tip'},
 {key:'Komisyon',label:'Komisyon',className:'commission'}
];
const money=(n,c)=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:c,maximumFractionDigits:0}).format(Number(n)||0);
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const parse=s=>new Date(`${s}T12:00:00`);
const startOf=(d,mode)=>{const x=new Date(d);x.setHours(12,0,0,0);if(mode==='week'){const day=(x.getDay()+6)%7;x.setDate(x.getDate()-day)}else if(mode==='month'){x.setDate(1)}else if(mode==='year'){x.setMonth(0,1)}return x};
const addStep=(d,mode)=>{const x=new Date(d);if(mode==='day')x.setDate(x.getDate()+1);else if(mode==='week')x.setDate(x.getDate()+7);else if(mode==='month')x.setMonth(x.getMonth()+1,1);else x.setFullYear(x.getFullYear()+1,0,1);return x};
const labelFor=(d,mode)=>{if(mode==='day')return new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(d);if(mode==='week')return new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(d);if(mode==='month')return new Intl.DateTimeFormat('tr-TR',{month:'short',year:'2-digit'}).format(d);return String(d.getFullYear())};
const titleFor=mode=>mode==='day'?'Günlük':mode==='week'?'Haftalık':mode==='month'?'Aylık':'Yıllık';

export default function AnalyticsChart({rows,currency,convert}){const[mode,setMode]=useState('month');
 const data=useMemo(()=>{const paid=rows.filter(r=>r.status==='Ödendi'&&SERIES.some(s=>s.key===r.type));if(!paid.length)return[];const dates=paid.map(r=>parse(r.date)).sort((a,b)=>a-b),first=startOf(dates[0],mode),last=startOf(dates[dates.length-1],mode),buckets=[];for(let d=new Date(first);d<=last;d=addStep(d,mode)){const item={key:iso(d),label:labelFor(d,mode)};SERIES.forEach(s=>item[s.key]=0);buckets.push(item)}const byKey=new Map(buckets.map(b=>[b.key,b]));paid.forEach(r=>{const k=iso(startOf(parse(r.date),mode)),bucket=byKey.get(k);if(bucket)bucket[r.type]+=convert(r)});return buckets},[rows,currency,convert,mode]);
 const width=Math.max(720,data.length*(mode==='day'?42:mode==='week'?68:mode==='month'?82:110)),height=300,pad={l:58,r:24,t:18,b:48};
 const maxValue=Math.max(1,...data.flatMap(d=>SERIES.map(s=>d[s.key]||0))),innerW=width-pad.l-pad.r,innerH=height-pad.t-pad.b,x=i=>pad.l+(data.length<=1?innerW/2:(i/(data.length-1))*innerW),y=v=>pad.t+innerH-(Number(v||0)/maxValue)*innerH,labelEvery=Math.max(1,Math.ceil(data.length/12));
 const totals=SERIES.map(s=>({s,total:data.reduce((sum,d)=>sum+Number(d[s.key]||0),0)}));
 return <section className="analysis line-chart-panel"><div className="analytics-head"><div><span className="eyebrow">FİNANS ANALİZİ</span><h2>{titleFor(mode)} kategori hareketleri</h2></div><div className="period-tabs"><button className={mode==='day'?'active':''} onClick={()=>setMode('day')}>Gün</button><button className={mode==='week'?'active':''} onClick={()=>setMode('week')}>Hafta</button><button className={mode==='month'?'active':''} onClick={()=>setMode('month')}>Ay</button><button className={mode==='year'?'active':''} onClick={()=>setMode('year')}>Yıl</button></div></div><div className="finance-legend">{totals.map(({s,total})=><span key={s.key}><i className={`legend-dot ${s.className}`}/><b>{s.label}</b><small>{money(total,currency)}</small></span>)}</div>{data.length?<div className="finance-line-scroll"><svg className="finance-line-svg" width={width} height={height} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${titleFor(mode)} finansal çizgi grafik`}><g className="finance-grid">{[0,.25,.5,.75,1].map(t=>{const value=maxValue*(1-t),yy=pad.t+innerH*t;return <g key={t}><line x1={pad.l} y1={yy} x2={width-pad.r} y2={yy}/><text x={pad.l-8} y={yy+4} textAnchor="end">{money(value,currency)}</text></g>})}</g><line className="finance-axis" x1={pad.l} y1={pad.t+innerH} x2={width-pad.r} y2={pad.t+innerH}/>{data.map((d,i)=>i%labelEvery===0||i===data.length-1?<text key={d.key} className="finance-x-label" x={x(i)} y={height-18} textAnchor="middle">{d.label}</text>:null)}{SERIES.map(s=>{const points=data.map((d,i)=>`${x(i)},${y(d[s.key])}`).join(' ');return <g key={s.key} className={`finance-series ${s.className}`}><polyline className="finance-line" points={points}/>{data.map((d,i)=><circle key={`${s.key}-${d.key}`} className="finance-point" cx={x(i)} cy={y(d[s.key])} r="3.2"><title>{`${d.label} • ${s.label}: ${money(d[s.key],currency)}`}</title></circle>)}</g>})}</svg></div>:<div className="finance-empty">Grafik için ödenmiş kayıt bulunmuyor.</div>}</section>}
