import React,{useEffect,useRef,useState}from'react';

const ROUTE='#varliklar-fon';
const PORTFOLIO={fundCode:'ALE',units:69442,averagePrice:13.04,fallbackPrice:13.584046,fallbackDailyReturn:0.0992};
const tl=value=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value)||0);
const num=(value,digits=2)=>new Intl.NumberFormat('tr-TR',{minimumFractionDigits:digits,maximumFractionDigits:digits}).format(Number(value)||0);
const pct=value=>`${Number(value||0)>=0?'+':''}${num(value,4)}%`;
const dateText=value=>value?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${String(value).slice(0,10)}T12:00:00`)):'—';
const timeText=value=>value?new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(value)):'—';

function RefreshIcon({size=18}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M20 11a8 8 0 1 0-2.34 5.66"/><path d="M20 4v7h-7"/></svg>}

function FundChart({history}){
 if(!history||history.length<2)return <div className="fund-chart-empty">TEFAS fiyat geçmişi bekleniyor. Yenile düğmesiyle tekrar deneyebilirsin.</div>;
 const width=1000,height=270,padX=26,padY=24,prices=history.map(x=>Number(x.price)).filter(Number.isFinite),min=Math.min(...prices),max=Math.max(...prices),range=max-min||1;
 const points=history.map((row,i)=>{const x=padX+(i/(history.length-1))*(width-padX*2),y=padY+((max-Number(row.price))/range)*(height-padY*2);return{x,y,row}});
 const line=points.map((p,i)=>`${i?'L':'M'} ${p.x.toFixed(2)} ${p.y.toFixed(2)}`).join(' '),last=points.at(-1);
 return <div className="fund-chart-wrap"><div className="fund-chart-meta"><div><span>1 Aylık Fon Fiyatı</span><strong>{num(last.row.price,6)} TL</strong></div><div className="fund-chart-stats"><span>En düşük <b>{num(min,6)}</b></span><span>En yüksek <b>{num(max,6)}</b></span></div></div><svg className="fund-chart" viewBox={`0 0 ${width} ${height}`} role="img" aria-label="ALE son bir aylık fon fiyat grafiği"><line x1={padX} x2={width-padX} y1={height/2} y2={height/2} className="fund-grid-line"/><line x1={padX} x2={width-padX} y1={padY} y2={padY} className="fund-grid-line"/><line x1={padX} x2={width-padX} y1={height-padY} y2={height-padY} className="fund-grid-line"/><path d={line} className="fund-line"/><circle cx={last.x} cy={last.y} r="5" className="fund-last-point"/>{points.map((p,i)=><circle key={`${p.row.date}-${i}`} cx={p.x} cy={p.y} r="9" className="fund-hit"><title>{`${dateText(p.row.date)} · ${num(p.row.price,6)} TL`}</title></circle>)}</svg><div className="fund-chart-dates"><span>{dateText(history[0].date)}</span><span>{dateText(history.at(-1).date)}</span></div></div>;
}

function FundDashboard({onClose}){
 const[data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[lastAttempt,setLastAttempt]=useState(null);
 const refresh=async()=>{if(loading)return;setLoading(true);setError('');setLastAttempt(new Date().toISOString());try{const response=await fetch(`/api/tefas?fund=${PORTFOLIO.fundCode}&_=${Date.now()}`,{cache:'no-store'});const json=await response.json();if(!response.ok)throw new Error(json?.detail||json?.error||'TEFAS verisi alınamadı.');setData(json)}catch(err){setError(err.message||'TEFAS bağlantı hatası.')}finally{setLoading(false)}};
 useEffect(()=>{refresh()},[]);
 const price=Number(data?.price??PORTFOLIO.fallbackPrice),dailyReturn=Number(data?.dailyReturn??PORTFOLIO.fallbackDailyReturn),total=PORTFOLIO.units*price,cost=PORTFOLIO.units*PORTFOLIO.averagePrice,totalProfit=total-cost,totalReturn=cost?totalProfit/cost*100:0;
 const latestHistory=data?.history?.at?.(-1),previousPrice=Number(data?.previousPrice||0),historyMatchesLatest=latestHistory&&Math.abs(Number(latestHistory.price)-price)<0.0000005;
 const dailyProfit=historyMatchesLatest&&previousPrice?PORTFOLIO.units*(price-previousPrice):(dailyReturn>-99?total-total/(1+dailyReturn/100):0);
 const live=Boolean(data?.price!==null&&data?.price!==undefined),sourceTime=data?.fetchedAt||lastAttempt;
 return <main className="assets-fund-page"><section className="assets-fund-shell"><div className="assets-page-top"><button type="button" className="assets-back" onClick={onClose}>← Muhasebeye dön</button><button type="button" className={`fund-refresh${loading?' loading':''}`} onClick={refresh} disabled={loading} title="TEFAS verisini yenile"><span className="refresh-icon"><RefreshIcon/></span><span>{loading?'TEFAS güncelleniyor':'TEFAS’tan güncelle'}</span></button></div><div className="assets-fund-heading fund-heading-row"><div><span className="eyebrow">VARLIKLAR / FON</span><h1>ALE · Para Piyasası (TL) Fonu</h1><p>Ak Portföy ALE fon pozisyonu ve TEFAS günlük verileri.</p></div><div className={`tefas-status ${live?'live':'fallback'}`}><i/>{live?'TEFAS VERİSİ':'SON BİLİNEN VERİ'}<small>{timeText(sourceTime)}</small></div></div>{error&&<div className="fund-warning"><strong>TEFAS bağlantısı kurulamadı.</strong><span>{error} · Ekranda son bilinen değerler gösteriliyor.</span></div>}<section className="fund-kpis"><article className="fund-kpi total"><span>Toplam Para</span><strong>{tl(total)}</strong><small>{num(PORTFOLIO.units,0)} adet ALE</small></article><article className={`fund-kpi ${dailyProfit>=0?'positive':'negative'}`}><span>Günlük Kazanç</span><strong>{dailyProfit>=0?'+':''}{tl(dailyProfit)}</strong><small>Son işlem gününe göre</small></article><article className={`fund-kpi ${dailyReturn>=0?'positive':'negative'}`}><span>Günlük Getiri (%)</span><strong>{pct(dailyReturn)}</strong><small>{data?.dailyReturnSource||'TEFAS son bilinen oran'}</small></article><article className={`fund-kpi ${totalProfit>=0?'positive':'negative'}`}><span>Toplam Kâr</span><strong>{totalProfit>=0?'+':''}{tl(totalProfit)}</strong><small>{pct(totalReturn)} maliyet getirisi</small></article><article className="fund-kpi"><span>Fon Adedi</span><strong>{num(PORTFOLIO.units,0)}</strong><small>ALE pay adedi</small></article><article className="fund-kpi"><span>Anlık Fon Fiyatı</span><strong>{num(price,6)} TL</strong><small>{data?.publishedDate?`${dateText(data.publishedDate)} TEFAS`:'Son bilinen fiyat'}</small></article></section><section className="fund-content-grid"><article className="fund-chart-card"><FundChart history={data?.history||[]}/></article><aside className="fund-details-card"><div className="fund-card-title"><span className="eyebrow">POZİSYON DETAYI</span><h2>ALE</h2></div><dl><div><dt>Ortalama maliyet</dt><dd>{num(PORTFOLIO.averagePrice,2)} TL</dd></div><div><dt>Toplam maliyet</dt><dd>{tl(cost)}</dd></div><div><dt>Güncel değer</dt><dd>{tl(total)}</dd></div><div><dt>Toplam kâr / zarar</dt><dd className={totalProfit>=0?'up':'down'}>{totalProfit>=0?'+':''}{tl(totalProfit)}</dd></div><div><dt>Fon kodu</dt><dd>{PORTFOLIO.fundCode}</dd></div><div><dt>Veri kaynağı</dt><dd><a href="https://www.tefas.gov.tr/tr/fon-detayli-analiz/ALE" target="_blank" rel="noreferrer">TEFAS ↗</a></dd></div></dl></aside></section></section></main>;
}

export default function AssetsNav(){
 const[active,setActive]=useState(()=>location.hash===ROUTE),[position,setPosition]=useState(null),buttonRef=useRef(null);
 useEffect(()=>{const sync=()=>setActive(location.hash===ROUTE);window.addEventListener('hashchange',sync);window.addEventListener('popstate',sync);return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('popstate',sync)}},[]);
 useEffect(()=>{const dashboard=document.querySelector('.main-dashboard.v7-dashboard');if(dashboard)dashboard.hidden=active;return()=>{if(dashboard)dashboard.hidden=false}},[active]);
 useEffect(()=>{let frame;const place=()=>{cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>{const currency=document.querySelector('.v7-header .currency');if(!currency){setPosition(null);return}const r=currency.getBoundingClientRect();setPosition({left:r.left-8,top:r.top,height:r.height})})};place();const observer=new MutationObserver(place);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('resize',place);window.addEventListener('scroll',place,{passive:true});return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('resize',place);window.removeEventListener('scroll',place)}},[]);
 const open=()=>{history.pushState(null,'',`${location.pathname}${location.search}${ROUTE}`);setActive(true);window.scrollTo({top:0,behavior:'auto'})};
 const close=()=>{history.pushState(null,'',`${location.pathname}${location.search}`);setActive(false);window.scrollTo({top:0,behavior:'auto'})};
 return <>{position&&<button ref={buttonRef} type="button" className={`btn secondary assets-nav-button assets-nav-fixed${active?' active':''}`} style={{left:position.left,top:position.top,height:position.height}} onClick={open}>VARLIKLAR / FON</button>}{active&&<FundDashboard onClose={close}/>}</>;
}
